<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Consultation;
use Carbon\Carbon;

class ConsultationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $now = Carbon::now();
        $consultations = [
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 1,
                'consultant_id' => 1,
                'consult_datetime' => $now->addDays(1),
                'end_consult_datetime' => $now->addDays(1)->addHour(),
                'title' => 'Pending Consultation 1',
                'desc' => 'Description of the pending consultation 1',
                'type' => 'Initial',
                'status' => 'pending',
                'link' => 'http://example.com/consultation/1',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 2,
                'consultant_id' => 2,
                'consult_datetime' => $now->addDays(2),
                'end_consult_datetime' => $now->addDays(2)->addHour(),
                'title' => 'Pending Consultation 2',
                'desc' => 'Description of the pending consultation 2',
                'type' => 'Initial',
                'status' => 'pending',
                'link' => 'http://example.com/consultation/2',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 3,
                'consultant_id' => 3,
                'consult_datetime' => $now->addDays(3),
                'end_consult_datetime' => $now->addDays(3)->addHour(),
                'title' => 'Pending Consultation 3',
                'desc' => 'Description of the pending consultation 3',
                'type' => 'Initial',
                'status' => 'pending',
                'link' => 'http://example.com/consultation/3',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 4,
                'consultant_id' => 4,
                'consult_datetime' => $now->addDays(4),
                'end_consult_datetime' => $now->addDays(4)->addHour(),
                'title' => 'Pending Consultation 4',
                'desc' => 'Description of the pending consultation 4',
                'type' => 'Initial',
                'status' => 'pending',
                'link' => 'http://example.com/consultation/4',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 5,
                'consultant_id' => 5,
                'consult_datetime' => $now->addDays(5),
                'end_consult_datetime' => $now->addDays(5)->addHour(),
                'title' => 'Coming Soon Consultation 1',
                'desc' => 'Description of the coming soon consultation 1',
                'type' => 'Follow-up',
                'status' => 'coming soon',
                'link' => 'http://example.com/consultation/5',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 6,
                'consultant_id' => 1,
                'consult_datetime' => $now->addDays(6),
                'end_consult_datetime' => $now->addDays(6)->addHour(),
                'title' => 'Coming Soon Consultation 2',
                'desc' => 'Description of the coming soon consultation 2',
                'type' => 'Follow-up',
                'status' => 'coming soon',
                'link' => 'http://example.com/consultation/6',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 7,
                'consultant_id' => 2,
                'consult_datetime' => $now->addDays(7),
                'end_consult_datetime' => $now->addDays(7)->addHour(),
                'title' => 'Coming Soon Consultation 3',
                'desc' => 'Description of the coming soon consultation 3',
                'type' => 'Follow-up',
                'status' => 'coming soon',
                'link' => 'http://example.com/consultation/7',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 8,
                'consultant_id' => 3,
                'consult_datetime' => $now->addDays(8),
                'end_consult_datetime' => $now->addDays(8)->addHour(),
                'title' => 'Coming Soon Consultation 4',
                'desc' => 'Description of the coming soon consultation 4',
                'type' => 'Follow-up',
                'status' => 'coming soon',
                'link' => 'http://example.com/consultation/8',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 9,
                'consultant_id' => 4,
                'consult_datetime' => $now->addDays(9),
                'end_consult_datetime' => $now->addDays(9)->addHour(),
                'title' => 'Ongoing Consultation 1',
                'desc' => 'Description of the ongoing consultation 1',
                'type' => 'Review',
                'status' => 'on going',
                'link' => 'http://example.com/consultation/9',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 10,
                'consultant_id' => 5,
                'consult_datetime' => $now->addDays(10),
                'end_consult_datetime' => $now->addDays(10)->addHour(),
                'title' => 'Ongoing Consultation 2',
                'desc' => 'Description of the ongoing consultation 2',
                'type' => 'Review',
                'status' => 'on going',
                'link' => 'http://example.com/consultation/10',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 1,
                'consultant_id' => 1,
                'consult_datetime' => $now->addDays(11),
                'end_consult_datetime' => $now->addDays(11)->addHour(),
                'title' => 'Ongoing Consultation 3',
                'desc' => 'Description of the ongoing consultation 3',
                'type' => 'Review',
                'status' => 'on going',
                'link' => 'http://example.com/consultation/11',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 2,
                'consultant_id' => 2,
                'consult_datetime' => $now->addDays(12),
                'end_consult_datetime' => $now->addDays(12)->addHour(),
                'title' => 'Ongoing Consultation 4',
                'desc' => 'Description of the ongoing consultation 4',
                'type' => 'Review',
                'status' => 'on going',
                'link' => 'http://example.com/consultation/12',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 3,
                'consultant_id' => 3,
                'consult_datetime' => $now->addDays(13),
                'end_consult_datetime' => $now->addDays(13)->addHour(),
                'title' => 'Finished Consultation 1',
                'desc' => 'Description of the finished consultation 1',
                'type' => 'Final',
                'status' => 'finished',
                'link' => 'http://example.com/consultation/13',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 4,
                'consultant_id' => 4,
                'consult_datetime' => $now->addDays(14),
                'end_consult_datetime' => $now->addDays(14)->addHour(),
                'title' => 'Finished Consultation 2',
                'desc' => 'Description of the finished consultation 2',
                'type' => 'Final',
                'status' => 'finished',
                'link' => 'http://example.com/consultation/14',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 5,
                'consultant_id' => 5,
                'consult_datetime' => $now->addDays(15),
                'end_consult_datetime' => $now->addDays(15)->addHour(),
                'title' => 'Finished Consultation 3',
                'desc' => 'Description of the finished consultation 3',
                'type' => 'Final',
                'status' => 'finished',
                'link' => 'http://example.com/consultation/15',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 6,
                'consultant_id' => 1,
                'consult_datetime' => $now->addDays(16),
                'end_consult_datetime' => $now->addDays(16)->addHour(),
                'title' => 'Finished Consultation 4',
                'desc' => 'Description of the finished consultation 4',
                'type' => 'Final',
                'status' => 'finished',
                'link' => 'http://example.com/consultation/16',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 7,
                'consultant_id' => 2,
                'consult_datetime' => $now->addDays(17),
                'end_consult_datetime' => $now->addDays(17)->addHour(),
                'title' => 'Cancelled Consultation 1',
                'desc' => 'Description of the cancelled consultation 1',
                'type' => 'Initial',
                'status' => 'cancelled',
                'link' => 'http://example.com/consultation/17',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 8,
                'consultant_id' => 3,
                'consult_datetime' => $now->addDays(18),
                'end_consult_datetime' => $now->addDays(18)->addHour(),
                'title' => 'Cancelled Consultation 2',
                'desc' => 'Description of the cancelled consultation 2',
                'type' => 'Follow-up',
                'status' => 'cancelled',
                'link' => 'http://example.com/consultation/18',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 9,
                'consultant_id' => 4,
                'consult_datetime' => $now->addDays(19),
                'end_consult_datetime' => $now->addDays(19)->addHour(),
                'title' => 'Cancelled Consultation 3',
                'desc' => 'Description of the cancelled consultation 3',
                'type' => 'Follow-up',
                'status' => 'cancelled',
                'link' => 'http://example.com/consultation/19',
            ],
            [
                'created_at' => $now,
                'updated_at' => $now,
                'user_id' => 10,
                'consultant_id' => 5,
                'consult_datetime' => $now->addDays(20),
                'end_consult_datetime' => $now->addDays(20)->addHour(),
                'title' => 'Cancelled Consultation 4',
                'desc' => 'Description of the cancelled consultation 4',
                'type' => 'Follow-up',
                'status' => 'cancelled',
                'link' => 'http://example.com/consultation/20',
            ],
        ];

        foreach ($consultations as $key => $value) {
            Consultation::create($value);
        }
    }
}
