<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProgrammingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('programming')->insert([
            'name' => 'Python',
            'name' => 'Java',
            'name' => 'JavaScript',
            'name' => 'C++',
            'name' => 'Ruby',
            'name' => 'Swift',
            'name' => 'C#',
            'name' => 'PHP',
            'name' => 'Go',
            'name' => 'Rust',
            'name' => 'Kotlin',
            'name' => 'TypeScript',
            'name' => 'Scala',
            'name' => 'Haskell',
            'name' => 'Perl',
            'name' => 'Lua',
            'name' => 'Dart',
            'name' => 'Objective-C',
            'name' => 'Assembly',
            'name' => 'SQL',
            'name' => 'Clojure',
            'name' => 'Erlang',
            'name' => 'Groovy',
            'name' => 'R',
            'name' => 'F#',
            'name' => 'Scheme',
            'name' => 'Smalltalk',
            'name' => 'Bash',
            'name' => 'PL/SQL',
            'name' => 'Fortran',
            'name' => 'Ada',
            'name' => 'Prolog',
            'name' => 'Lisp',
            'name' => 'COBOL',
            'name' => 'MATLAB',
            'name' => 'Delphi',
            'name' => 'Objective-C',
            'name' => 'ActionScript',
            'name' => 'Visual Basic',
            'name' => 'VBScript',
            'name' => 'Elixir',
            'name' => 'Julia',
            'name' => 'OCaml',
            'name' => 'Django',
            'name' => 'AngularJS',
            'name' => 'React',
            'name' => 'Vue.js',
            'name' => 'Ember.js',
            'name' => 'Backbone.js',
            'name' => 'Meteor.js',
            'name' => 'Express.js',
            'name' => 'Flask',
            'name' => 'Spring',
            'name' => 'Hibernate',
            'name' => 'Laravel',
            'name' => 'Symfony',
            'name' => 'CodeIgniter',
            'name' => 'CakePHP',
            'name' => 'Zend Framework',
            'name' => 'ASP.NET',
            'name' => 'Node.js',
            'name' => 'Ruby on Rails',
            'name' => 'Django',
            'name' => 'Flask',
            'name' => 'Pyramid',
            'name' => 'CherryPy',
            'name' => 'TurboGears',
            'name' => 'Plone',
            'name' => 'Django CMS',
            'name' => 'WordPress',
            'name' => 'Joomla',
            'name' => 'Drupal',
            'name' => 'Magento',
            'name' => 'Shopify',
            'name' => 'OpenCart',
            'name' => 'PrestaShop',
            'name' => 'BigCommerce',
            'name' => 'WooCommerce',
            'name' => 'osCommerce',
            'name' => 'Zen Cart',
            'name' => 'Spree Commerce',
            'name' => 'Symfony',
            'name' => 'Laravel',
            'name' => 'CodeIgniter',
            'name' => 'Zend Framework',
            'name' => 'CakePHP',
            'name' => 'Yii',
            'name' => 'Phalcon',
            'name' => 'FuelPHP',
            'name' => 'Slim',
            'name' => 'Lumen',
            'name' => 'Silex',
            'name' => 'F3',
            'name' => 'Pop PHP',
            'name' => 'Aura'
        ]);
    }
}
